// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.2
// 	protoc        v5.26.1
// source: qr.proto

package qr_proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateQROut struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Qr string `protobuf:"bytes,1,opt,name=qr,proto3" json:"qr,omitempty"`
}

func (x *CreateQROut) Reset() {
	*x = CreateQROut{}
	mi := &file_qr_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateQROut) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateQROut) ProtoMessage() {}

func (x *CreateQROut) ProtoReflect() protoreflect.Message {
	mi := &file_qr_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateQROut.ProtoReflect.Descriptor instead.
func (*CreateQROut) Descriptor() ([]byte, []int) {
	return file_qr_proto_rawDescGZIP(), []int{0}
}

func (x *CreateQROut) GetQr() string {
	if x != nil {
		return x.Qr
	}
	return ""
}

type VerifyQRIn struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
}

func (x *VerifyQRIn) Reset() {
	*x = VerifyQRIn{}
	mi := &file_qr_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyQRIn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyQRIn) ProtoMessage() {}

func (x *VerifyQRIn) ProtoReflect() protoreflect.Message {
	mi := &file_qr_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyQRIn.ProtoReflect.Descriptor instead.
func (*VerifyQRIn) Descriptor() ([]byte, []int) {
	return file_qr_proto_rawDescGZIP(), []int{1}
}

func (x *VerifyQRIn) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type VerifyQROut struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AccessGranted bool `protobuf:"varint,1,opt,name=access_granted,json=accessGranted,proto3" json:"access_granted,omitempty"`
}

func (x *VerifyQROut) Reset() {
	*x = VerifyQROut{}
	mi := &file_qr_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyQROut) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyQROut) ProtoMessage() {}

func (x *VerifyQROut) ProtoReflect() protoreflect.Message {
	mi := &file_qr_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyQROut.ProtoReflect.Descriptor instead.
func (*VerifyQROut) Descriptor() ([]byte, []int) {
	return file_qr_proto_rawDescGZIP(), []int{2}
}

func (x *VerifyQROut) GetAccessGranted() bool {
	if x != nil {
		return x.AccessGranted
	}
	return false
}

var File_qr_proto protoreflect.FileDescriptor

var file_qr_proto_rawDesc = []byte{
	0x0a, 0x08, 0x71, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74,
	0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x1d, 0x0a, 0x0b, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x51, 0x52, 0x4f, 0x75, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x71, 0x72, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x02, 0x71, 0x72, 0x22, 0x22, 0x0a, 0x0a, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79,
	0x51, 0x52, 0x49, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x34, 0x0a, 0x0b, 0x56, 0x65,
	0x72, 0x69, 0x66, 0x79, 0x51, 0x52, 0x4f, 0x75, 0x74, 0x12, 0x25, 0x0a, 0x0e, 0x61, 0x63, 0x63,
	0x65, 0x73, 0x73, 0x5f, 0x67, 0x72, 0x61, 0x6e, 0x74, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x0d, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x47, 0x72, 0x61, 0x6e, 0x74, 0x65, 0x64,
	0x32, 0x68, 0x0a, 0x09, 0x51, 0x52, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x32, 0x0a,
	0x08, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x51, 0x52, 0x12, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74,
	0x79, 0x1a, 0x0c, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x51, 0x52, 0x4f, 0x75, 0x74, 0x22,
	0x00, 0x12, 0x27, 0x0a, 0x08, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x51, 0x52, 0x12, 0x0b, 0x2e,
	0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x51, 0x52, 0x49, 0x6e, 0x1a, 0x0c, 0x2e, 0x56, 0x65, 0x72,
	0x69, 0x66, 0x79, 0x51, 0x52, 0x4f, 0x75, 0x74, 0x22, 0x00, 0x42, 0x0c, 0x5a, 0x0a, 0x2e, 0x2f,
	0x71, 0x72, 0x2d, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_qr_proto_rawDescOnce sync.Once
	file_qr_proto_rawDescData = file_qr_proto_rawDesc
)

func file_qr_proto_rawDescGZIP() []byte {
	file_qr_proto_rawDescOnce.Do(func() {
		file_qr_proto_rawDescData = protoimpl.X.CompressGZIP(file_qr_proto_rawDescData)
	})
	return file_qr_proto_rawDescData
}

var file_qr_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_qr_proto_goTypes = []any{
	(*CreateQROut)(nil),   // 0: CreateQROut
	(*VerifyQRIn)(nil),    // 1: VerifyQRIn
	(*VerifyQROut)(nil),   // 2: VerifyQROut
	(*emptypb.Empty)(nil), // 3: google.protobuf.Empty
}
var file_qr_proto_depIdxs = []int32{
	3, // 0: QRService.CreateQR:input_type -> google.protobuf.Empty
	1, // 1: QRService.VerifyQR:input_type -> VerifyQRIn
	0, // 2: QRService.CreateQR:output_type -> CreateQROut
	2, // 3: QRService.VerifyQR:output_type -> VerifyQROut
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_qr_proto_init() }
func file_qr_proto_init() {
	if File_qr_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_qr_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_qr_proto_goTypes,
		DependencyIndexes: file_qr_proto_depIdxs,
		MessageInfos:      file_qr_proto_msgTypes,
	}.Build()
	File_qr_proto = out.File
	file_qr_proto_rawDesc = nil
	file_qr_proto_goTypes = nil
	file_qr_proto_depIdxs = nil
}
